# File: .github/workflows/caching.yml

name: Tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      # Set up GitHub Actions caching for Wireit.
      - uses: google/wireit@setup-github-actions-caching/v1

      # Install npm dependencies.
      - run: npm ci

      # Setup Wireit globally
      - run: npm install -g wireit

      # Run build. Wireit will automatically use
      # the GitHub Actions cache whenever possible.
      - run: npm run build